import React from 'react';
import { 
  Sliders, 
  Video, 
  Terminal, 
  Send, 
  Bot, 
  User, 
  Activity, 
  Layers, 
  Cpu, 
  Play, 
  RotateCcw,
  Sparkles,
  Zap,
  HelpCircle
} from 'lucide-react';

interface UnrealBridgeProps {
  unrealConfig: {
    engineVersion: string;
    pixelStreamingPort: number;
    streamActive: boolean;
    fps: number;
    shaderCount: number;
    shaderCompiled: boolean;
    lightingPreset: string;
    faceRig: {
      blink: number;
      mouthOpen: number;
      neckTilt: number;
      creativeExpressiveness: number;
      microDetails: number;
    };
  };
  setUnrealConfig: React.Dispatch<React.SetStateAction<any>>;
  evaChatMessages: { role: 'user' | 'assistant'; content: string }[];
  evaInputText: string;
  setEvaInputText: (txt: string) => void;
  evaIsThinking: boolean;
  unrealLogs: string[];
  handleSendEvaMessage: (e?: React.FormEvent) => void;
}

export default function UnrealBridge({
  unrealConfig,
  setUnrealConfig,
  evaChatMessages,
  evaInputText,
  setEvaInputText,
  evaIsThinking,
  unrealLogs,
  handleSendEvaMessage
}: UnrealBridgeProps) {
  
  const handleSliderChange = (key: string, val: number) => {
    setUnrealConfig((prev: any) => ({
      ...prev,
      faceRig: {
        ...prev.faceRig,
        [key]: val
      }
    }));
  };

  const handlePresetChange = (preset: string) => {
    setUnrealConfig((prev: any) => ({
      ...prev,
      lightingPreset: preset
    }));
    // Add log
    unrealLogs.unshift(`[Render] Lighting set to preset: "${preset}"`);
  };

  const resetRig = () => {
    setUnrealConfig((prev: any) => ({
      ...prev,
      faceRig: {
        blink: 12,
        mouthOpen: 0,
        neckTilt: 5,
        creativeExpressiveness: 80,
        microDetails: 95
      }
    }));
  };

  // Image generated by AI Studio
  const evaImage = "/src/assets/images/metahuman_eva_render_1784065181087.jpg";

  return (
    <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-6 w-full max-w-7xl mx-auto">
      
      {/* LEFT COLUMN: PARAMETERS & ENGINE TUNING (5 cols) */}
      <div className="lg:col-span-5 flex flex-col gap-6">
        
        {/* Unreal Live Stream Configuration */}
        <div className="bg-indigo-950/95 border border-indigo-900 rounded-[24px] p-5 text-white shadow-xl flex flex-col gap-4">
          <div className="flex justify-between items-center border-b border-indigo-900/60 pb-3">
            <div className="flex items-center gap-2">
              <Video className="w-5 h-5 text-indigo-400" />
              <h3 className="font-serif italic text-base font-bold text-indigo-100">Unreal Engine 5.4.3 Bridge</h3>
            </div>
            <span className="text-[10px] uppercase font-mono tracking-wider bg-indigo-500/20 px-2.5 py-1 rounded-full text-indigo-300 border border-indigo-500/30">
              Live Link Connected
            </span>
          </div>

          <div className="grid grid-cols-2 gap-4 text-xs font-mono">
            <div className="bg-indigo-900/35 p-3 rounded-xl border border-indigo-900/55">
              <span className="block text-[10px] opacity-60 uppercase mb-1">Pixel Stream Port</span>
              <span className="font-bold text-indigo-200">Localhost:{unrealConfig.pixelStreamingPort}</span>
            </div>
            <div className="bg-indigo-900/35 p-3 rounded-xl border border-indigo-900/55">
              <span className="block text-[10px] opacity-60 uppercase mb-1">Renderer Status</span>
              <span className="font-bold text-emerald-400 flex items-center gap-1">
                <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full inline-block animate-ping"></span>
                60 FPS (RTX 4090)
              </span>
            </div>
            <div className="bg-indigo-900/35 p-3 rounded-xl border border-indigo-900/55">
              <span className="block text-[10px] opacity-60 uppercase mb-1">Shader Cache</span>
              <span className="font-bold text-indigo-200">Ready ({unrealConfig.shaderCount} compiled)</span>
            </div>
            <div className="bg-indigo-900/35 p-3 rounded-xl border border-indigo-900/55">
              <span className="block text-[10px] opacity-60 uppercase mb-1">Substrate Shader</span>
              <span className="font-bold text-indigo-200">Nanite active</span>
            </div>
          </div>

          {/* Lighting Presets selection */}
          <div className="flex flex-col gap-2">
            <span className="text-[10px] uppercase tracking-wider font-mono opacity-70">Unreal Lighting Environment</span>
            <div className="grid grid-cols-3 gap-2">
              {['Studio Neutral', 'Golden Hour', 'Moonlight Noir'].map((p) => (
                <button
                  key={p}
                  onClick={() => handlePresetChange(p)}
                  className={`text-[10px] font-bold py-2 px-1 rounded-lg border transition-all ${
                    unrealConfig.lightingPreset === p
                      ? 'bg-indigo-500 text-white border-indigo-400'
                      : 'bg-indigo-900/20 text-indigo-200 border-indigo-900 hover:bg-indigo-900/40'
                  }`}
                >
                  {p}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* MetaHuman Face Rig Configuration */}
        <div className="bg-white border border-[#e2e1d5] rounded-[24px] p-5 shadow-sm flex flex-col gap-4">
          <div className="flex justify-between items-center border-b border-[#e2e1d5] pb-3">
            <div className="flex items-center gap-2">
              <Sliders className="w-5 h-5 text-[#5A5A40]" />
              <h3 className="font-serif italic text-base font-bold text-gray-900">MetaHuman Rig Controls</h3>
            </div>
            <button 
              onClick={resetRig}
              className="text-[10px] hover:text-[#5A5A40] flex items-center gap-1 transition-colors font-semibold uppercase font-mono"
              title="Gjenopprett rig til standard"
            >
              <RotateCcw className="w-3 h-3" /> Resett rig
            </button>
          </div>

          <p className="text-xs text-gray-500">
            Disse DNA-parametrene justerer ansiktsriggen til Eva-01 live i det virtuelle simuleringskameraet.
          </p>

          <div className="space-y-4 text-xs">
            {/* Blink shape */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between font-mono text-[10px] text-gray-500">
                <span>Øye-blink (Blink Shape)</span>
                <span className="font-bold text-[#5A5A40]">{unrealConfig.faceRig.blink}%</span>
              </div>
              <input 
                type="range" 
                min="0" 
                max="100" 
                value={unrealConfig.faceRig.blink}
                onChange={(e) => handleSliderChange('blink', parseInt(e.target.value))}
                className="w-full accent-[#5A5A40] cursor-pointer"
              />
            </div>

            {/* Mouth open */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between font-mono text-[10px] text-gray-500">
                <span>Munnåpning (Mouth Open / Speech)</span>
                <span className="font-bold text-[#5A5A40]">{unrealConfig.faceRig.mouthOpen}%</span>
              </div>
              <input 
                type="range" 
                min="0" 
                max="100" 
                value={unrealConfig.faceRig.mouthOpen}
                onChange={(e) => handleSliderChange('mouthOpen', parseInt(e.target.value))}
                className="w-full accent-[#5A5A40] cursor-pointer"
              />
            </div>

            {/* Neck Tilt */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between font-mono text-[10px] text-gray-500">
                <span>Nakketilt (Neck Tilt Yaw)</span>
                <span className="font-bold text-[#5A5A40]">{unrealConfig.faceRig.neckTilt}°</span>
              </div>
              <input 
                type="range" 
                min="-45" 
                max="45" 
                value={unrealConfig.faceRig.neckTilt}
                onChange={(e) => handleSliderChange('neckTilt', parseInt(e.target.value))}
                className="w-full accent-[#5A5A40] cursor-pointer"
              />
            </div>

            {/* Creative Expressiveness */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between font-mono text-[10px] text-gray-500">
                <span>Kreativ Ekspressivitet (Emotional Blend)</span>
                <span className="font-bold text-[#5A5A40]">{unrealConfig.faceRig.creativeExpressiveness}%</span>
              </div>
              <input 
                type="range" 
                min="0" 
                max="100" 
                value={unrealConfig.faceRig.creativeExpressiveness}
                onChange={(e) => handleSliderChange('creativeExpressiveness', parseInt(e.target.value))}
                className="w-full accent-[#5A5A40] cursor-pointer"
              />
            </div>

            {/* Micro Details */}
            <div className="flex flex-col gap-1">
              <div className="flex justify-between font-mono text-[10px] text-gray-500">
                <span>Hud-mikrodetaljer (Skin Micro-relief)</span>
                <span className="font-bold text-[#5A5A40]">{unrealConfig.faceRig.microDetails}%</span>
              </div>
              <input 
                type="range" 
                min="0" 
                max="100" 
                value={unrealConfig.faceRig.microDetails}
                onChange={(e) => handleSliderChange('microDetails', parseInt(e.target.value))}
                className="w-full accent-[#5A5A40] cursor-pointer"
              />
            </div>
          </div>
        </div>
      </div>

      {/* RIGHT COLUMN: HIGH-FIDELITY RENDER & CHAT BOARD (7 cols) */}
      <div className="lg:col-span-7 flex flex-col gap-6">
        
        {/* Virtual Character Render Stage */}
        <div className="bg-[#1c1c24] border border-gray-800 rounded-[32px] overflow-hidden shadow-2xl flex flex-col relative aspect-video md:aspect-auto md:h-[450px]">
          
          {/* Active Overlay stats */}
          <div className="absolute top-4 left-4 z-10 flex flex-col gap-1 font-mono text-[10px] text-white/80 bg-black/55 backdrop-blur-md p-2.5 rounded-xl border border-white/10 pointer-events-none">
            <span className="flex items-center gap-1.5 text-emerald-400 font-bold uppercase">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
              Eva-01 (METAHUMAN)
            </span>
            <span>RHI: Vulkan (SM6)</span>
            <span>Substrate: Active</span>
            <span>DNA Link: Confirmed</span>
            <span className="text-amber-400 uppercase tracking-widest font-bold mt-1 text-[8px]">
              Preset: {unrealConfig.lightingPreset}
            </span>
          </div>

          <div className="absolute top-4 right-4 z-10 font-mono text-[10px] bg-indigo-900/80 backdrop-blur-md text-indigo-200 border border-indigo-700/50 px-2.5 py-1 rounded-lg">
            UE5.4.3 STREAM PORT: 3000
          </div>

          {/* Actual Character Render Mockup */}
          <div className="flex-1 w-full relative flex items-center justify-center overflow-hidden bg-radial-gradient">
            <img 
              src={evaImage}
              alt="MetaHuman Eva-01" 
              className="w-full h-full object-cover object-center transition-all duration-700 hover:scale-105"
              referrerPolicy="no-referrer"
            />
            
            {/* Speech Wave Overlays (Pulsing bars when she is "thinking" or "speaking") */}
            {(evaIsThinking || unrealConfig.faceRig.mouthOpen > 0) && (
              <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2 bg-black/60 backdrop-blur-md px-6 py-2.5 rounded-full border border-white/10 flex items-center gap-2">
                <span className="text-[10px] font-mono text-indigo-300 uppercase tracking-wider animate-pulse">
                  {evaIsThinking ? 'Eva tenker...' : 'Livelink Audio aktiv'}
                </span>
                <div className="flex items-end gap-1 h-3">
                  <div className={`w-0.5 bg-indigo-400 rounded-full animate-[pulse_0.6s_infinite] ${evaIsThinking ? 'h-2' : 'h-3'}`}></div>
                  <div className={`w-0.5 bg-indigo-400 rounded-full animate-[pulse_0.4s_infinite] ${evaIsThinking ? 'h-1' : 'h-2'}`}></div>
                  <div className={`w-0.5 bg-indigo-400 rounded-full animate-[pulse_0.8s_infinite] ${evaIsThinking ? 'h-3' : 'h-1'}`}></div>
                  <div className={`w-0.5 bg-indigo-400 rounded-full animate-[pulse_0.5s_infinite] ${evaIsThinking ? 'h-2' : 'h-3'}`}></div>
                </div>
              </div>
            )}
          </div>

          {/* Subtitle / Output Box */}
          <div className="bg-black/90 p-4 border-t border-gray-800 text-white flex flex-col gap-2 shrink-0 max-h-[160px] overflow-y-auto">
            <span className="text-[10px] font-bold uppercase tracking-widest text-indigo-400 flex items-center gap-1 font-mono">
              <Bot className="w-3 h-3" /> Undertekster & Dialoglogg
            </span>
            <p className="text-xs text-gray-300 leading-relaxed italic">
              "{evaChatMessages[evaChatMessages.length - 1]?.content || 'Klar til å simulere...'}"
            </p>
          </div>
        </div>

        {/* Live Interactive Dialogue Terminal */}
        <div className="bg-white border border-[#e2e1d5] rounded-[24px] p-5 shadow-sm flex flex-col gap-4 flex-1">
          <div className="flex justify-between items-center border-b border-[#e2e1d5] pb-2">
            <h4 className="font-serif italic text-sm font-bold text-gray-900 flex items-center gap-1.5">
              <Sparkles className="w-4 h-4 text-indigo-600" /> Spør MetaHuman-partneren din
            </h4>
            <span className="text-[9px] font-mono bg-indigo-50 text-indigo-700 border border-indigo-100 px-2.5 py-0.5 rounded-full">
              Kognitiv Modul: Gemini 3.5 Flash
            </span>
          </div>

          {/* Chat scrolling log */}
          <div className="flex-1 overflow-y-auto pr-1 space-y-3 max-h-[180px] text-xs">
            {evaChatMessages.slice(-3).map((msg, i) => (
              <div 
                key={i} 
                className={`p-2.5 rounded-xl border ${
                  msg.role === 'user' 
                    ? 'bg-indigo-50 border-indigo-100 text-[#2c2c24] ml-auto max-w-[85%]' 
                    : 'bg-stone-50 border-stone-200 text-[#2c2c24] max-w-[85%]'
                }`}
              >
                <div className="font-bold text-[10px] uppercase tracking-wider mb-1 opacity-65 flex items-center gap-1">
                  {msg.role === 'user' ? <User className="w-3 h-3" /> : <Bot className="w-3 h-3 text-indigo-600" />}
                  {msg.role === 'user' ? 'Forsker' : 'Eva-01 (Virtual Partner)'}
                </div>
                <p>{msg.content}</p>
              </div>
            ))}
          </div>

          {/* Prompt quick items */}
          <div className="flex flex-wrap gap-1.5">
            {[
              'Hvilke biologiske styrker har Ganoderma-mycel?',
              'Hvordan påvirkes herdingen av kalkstein av temperatur?',
              'Kan du simulere trykkfastheten i en trekonstruksjon?'
            ].map((p, idx) => (
              <button
                key={idx}
                onClick={() => setEvaInputText(p)}
                className="text-[10px] bg-[#eeede6]/55 border border-[#dcdad0] hover:bg-indigo-50 hover:border-indigo-200 text-[#2c2c24] py-1.5 px-2.5 rounded-lg transition-all font-medium text-left"
              >
                {p}
              </button>
            ))}
          </div>

          {/* Dialog Input Form */}
          <form onSubmit={handleSendEvaMessage} className="flex gap-2">
            <input 
              type="text" 
              placeholder="Skriv inn en forskningskommando eller spørsmål..."
              value={evaInputText}
              onChange={(e) => setEvaInputText(e.target.value)}
              className="flex-1 bg-[#fcfcf9] border border-[#dcdad0] focus:border-indigo-500 rounded-xl py-2 px-3 text-xs focus:outline-none text-[#2c2c24]"
            />
            <button
              type="submit"
              disabled={evaIsThinking || !evaInputText.trim()}
              className="bg-indigo-950 text-white px-4 rounded-xl hover:bg-indigo-900 transition-all flex items-center gap-1 text-xs font-bold disabled:opacity-40"
            >
              <Send className="w-3.5 h-3.5" /> Send
            </button>
          </form>
        </div>

        {/* Engine scrolling developer terminal */}
        <div className="bg-neutral-900 text-neutral-300 font-mono text-[10px] p-4 rounded-2xl border border-neutral-800 flex flex-col gap-2 max-h-[140px] shrink-0">
          <div className="flex justify-between items-center border-b border-neutral-800 pb-1.5">
            <span className="text-[9px] uppercase tracking-wider font-bold text-indigo-400 flex items-center gap-1">
              <Terminal className="w-3 h-3" /> Unreal Engine Stream Diagnostics (Port 3000)
            </span>
            <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full inline-block animate-pulse"></span>
          </div>
          <div className="overflow-y-auto space-y-1.5 max-h-[90px] pr-1">
            {unrealLogs.map((log, i) => (
              <div key={i} className="flex gap-2 text-left">
                <span className="opacity-40 shrink-0">[{new Date().toLocaleTimeString()}]</span>
                <span className={
                  log.includes('[System]') ? 'text-blue-400' :
                  log.includes('[Render]') ? 'text-purple-400' :
                  log.includes('[Predictive AI]') ? 'text-amber-400' :
                  log.includes('[Database]') ? 'text-emerald-400' : 'text-neutral-300'
                }>{log}</span>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
